### ISSUE TITLE
standardError being called with NULL weights under M3, but standardError has no handling for NULL weights

### ISSUE THREAD

**Issue by nievergeltlab** [e-jorsboe/asaMap#1]
in asaMap.cpp, line 1458 (this is where it looks like M4 is estimated), it says:

" standardError(p->start,p->design,p->ysCgs,p->ys,p->len,p->p_sCg,p->regression,p->SE,NULL,p->index);"

based on the description of the function, it is being called with NULL value for weights. Looking at the standardError function itself, it starts with the statement 

"if(weights!=NULL){"

but there is no else statement and return value for the circumstance where weights = NULL. This results in the following error:

"double free or corruption (!prev)"

On compilation, the compiler seems to vaguely warn about this:

"asaMap.cpp:1146:1: warning: control reaches end of non-void function "

**Comment by e-jorsboe** [comment]
Hi Adam,

You are quite right, the issue was that the standardError function was supposed to return a double, however it would not return a double in the else statement. I have therefore changed it to a void function, and removed the return statement. If there is an issue with the weights is checked prior to the standardError function. This should therefore no longer be an issue.

So thank you for pointing out this error! I hope you can run your analyses now?

Best,
Emil

**Comment by nievergeltlab** [comment]
Indeed, it now runs perfectly!

Thanks
Adam
